#intent constatnt
INTENT_OPEN_YOUTUBE = "OPEN_YOUTUBE"
INTENT_TIME = "TIME"
INTENT_EXIT = "EXIT"
INTENT_UNKNOWN="UNKNOWN"
INTENT_REMEMBER = "REMEMBER"
INTENT_RECALL = "RECALL"
INTENT_LIST_MEMORY = "LIST_MEMORY"

#system signal
EXIT_SIGNAL = "EXIT_SIGNAL"

#responses
UNKNOWN_RESPONSE = "I did not understand the command."

#loop setting
SLEEP_TIME=1